### ISSUE TITLE
Add Test cases for local SearchStore

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#57]
The file is frontend/lib/store/local-history.ts

**Comment by Riyan-Mo** [comment]
I would like to take on this issue.

**Comment by ahaapple** [comment]
@Riyan-Mo Assigned, thanks.

**Comment by DDibyajyot** [comment]
@Riyan-Mo Hey just wanted to update, you could have a look at jest library for testing, since it's already set up and would be better for uniform testing, jest config etc have been set up, you would just need to add the test in lib/store/tests. 
@ahaapple maybe you could have a look and update the testing guidelines, or maybe we could raise an issue which I'll be happy to update the guidelines for testing for any future issues.

**Comment by ahaapple** [comment]
https://github.com/memfreeme/memfree/issues/86 @DDibyajyot Thanks. this is the issue.

**Comment by Riyan-Mo** [comment]
@DDibyajyot I will, Thank you.

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?
